name: deploy-pipeline
run-name: ${{ github.repository }} deploy pipeline
on:
  schedule:
    - cron: '30 13 * * *'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        options: 
        - dev
        default: dev
      destroy:
        type: boolean
        description: Destroy Terraform
        default: false

jobs:
  deploy:
    name: 'Deploy ${{ github.event.inputs.environment }}'
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      DESTROY: ${{ github.event.inputs.destroy }}
      TF_INPUT: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_CONTAINER_TOKEN: ${{ secrets.IW_GITHUB_CONTAINER_TOKEN }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the variables
        env:
          DEFAULT_ENV: 'dev'
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment || env.DEFAULT_ENV }}" >> $GITHUB_ENV
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "DESTROY=true" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: Terraform Init
        run: |
          terraform init -backend-config="key=${{ env.REPO_NAME }}-${{ env.ENVIRONMENT }}.tfstate"

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        if: github.event.inputs.destroy == 'false'
        id: plan
        run: |
          terraform plan -out=plan.out -var-file="tfvars/${{ env.ENVIRONMENT }}.tfvars"

      - name: Terraform Apply
        if: github.event.inputs.destroy == 'false'
        run: |
          terraform apply -auto-approve plan.out

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'  || ${{ env.DESTROY }} == 'true'
        run: |


        # terraform destroy -auto-approve -var-file="tfvars/${{ env.ENVIRONMENT }}.tfvars"

      - name: Configure AWS credentials
        if: github.event.inputs.destroy == 'false'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Update kube config
        if: github.event.inputs.destroy == 'false'
        run: aws eks update-kubeconfig --name iw-eks-cluster --region ap-southeast-2

      - name: Set up Kubectl
        if: github.event.inputs.destroy == 'false'
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.29.0'

      - name: Create Docker Registry Secret
        run: |
          kubectl create secret docker-registry github-token \
            --docker-server=ghcr.io \
            --docker-username=sladebutler \
            --docker-password=${{ env.GITHUB_CONTAINER_TOKEN }} 
